### PR TITLE
feat: added LLC calculations

### PR DESCRIPTION
**Pull request by rzuljevic**
I'm currently deciding which type of company I want to open and came across your calculator. I felt like it was missing calculations for LLC with yearly bonus so I added it.

### CODE REVIEW

**Comment by turanjanin** [comment]
Looking good, thanks for the contribution.

Can you just alter the logic a little bit? Instead of asking the user to provide the desired neto salary in foreign currency, I think it's better to work immediately with neto salary in RSD and to populate the field with the minimal neto salary. After that, the logic can remain the same.

Also, to add more clarification, I suggest updating the labels so that it's obvious that the first calculation is for 11 salaries and the second one is for the 12th salary which includes the bonus.

**Comment by turanjanin** [comment]
Also, on an unrelated note, do you think we should also consider adding an LLC option with 12 equal salaries and dividend payout? Or that's way too expensive in comparison with other options?

**Comment by rzuljevic** [comment]
> Looking good, thanks for the contribution.
> 
> Can you just alter the logic a little bit? Instead of asking the user to provide the desired neto salary in foreign currency, I think it's better to work immediately with neto salary in RSD and to populate the field with the minimal neto salary. After that, the logic can remain the same.
> 
> Also, to add more clarification, I suggest updating the labels so that it's obvious that the first calculation is for 11 salaries and the second one is for the 12th salary which includes the bonus.

Thanks! Wanted to support the app as it will definitely be useful.

Both of the suggestions should be addressed now.

**Comment by rzuljevic** [comment]
> Also, on an unrelated note, do you think we should also consider adding an LLC option with 12 equal salaries and dividend payout? Or that's way too expensive in comparison with other options?

I think it could make sense to make it since it could be an option for someone with very large earnings (hundreds of thousands of eur per month), since you don't pay yearly income tax 10%/15% on dividend. But I think if you earn that kind of money you have someone to take care of it.

**Pull request merged**
